# Install this sample config to ~/.config/rancher/rancher.yml
branch:
  type: feat
  separator: "/"
  description-separator: "-"
types:
  Feature: feature
  Feat: feat
  Fix: fix
  Chore: chore
  Docs: docs
  Refactor: refactor
  Performance: perf
  CI: ci
  None:
# jira:
#   username: <username>
#   query: assignee=currentUser() and sprint IN openSprints()
#   token: <token>
#   host: <host>.atlassian.net
#   suffix-ticket-id: false
